version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 2s
      retries: 5
    networks: [appnet]
  
  redis:
    image: redis:6-alpine 
    networks: [appnet]
    volumes:
      - redis_data:/data 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 3 

  proxy:
      image: nginx:latest  # שימוש באימג' Nginx רשמי
      volumes:
        # **מיפוי הקובץ:** קח את הקונפיגורציה המקומית וטען אותה למיקום הנכון בתוך הקונטיינר
        - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - api
        - ui
      ports:
        # **חשיפה יחידה:** רק הפרוקסי חשוף לעולם החיצון (דרך פורט 80)
        - "80:80"
      networks: [appnet]
      
  api:
    build: ./api
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/postgres
      REDIS_HOST: redis 
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks: [appnet]

  ui:
    build: ./ui
    depends_on: [api]
    networks: [appnet]

networks:
  appnet:
    driver: bridge

volumes:
  redis_data: